### ISSUE TITLE
Unittest Shortcut not working

### ISSUE THREAD

**Issue by maurerle** [spyder-ide/spyder-unittest#172]
## Description of your problem

After setting the "Run Unittest" shortcut in spyder preferences -> keyboard shortcuts to Alt+Shift+F11, it is not callable through the shortcut

## What steps will reproduce the problem?

1. Spyder Preferences -> Keyboard Shortcut -> search test
2. Enter Shortcut
3. Apply & test shortcut

## What is the expected output? What do you see instead?

Nothing happens. I'd expect it to trigger the action like clicking the UI button in Run -> Run unit tests

### Paste traceback/error below (if applicable)
*(Copy from error dialog or `View > Panes > Internal Console`)*

```python-traceback

<!--- PASTE TRACEBACK HERE --->

```

## Key versions and other information:

* Spyder version: 5.2.2
* Version of spyder-unittest plugin: 0.5.0
* Installation method for Spyder and the unittest plugin:pip
* Python version: 3.9.7
* Testing framework used: pytest
* Testing framework version: 6.2.5
* Operating system: GNU/Linux Debian 11 Bullseye

**Comment by jitseniesen** [comment]
In Spyder v4, if I remember correctly, the shortcut was set to Alt+Shift+F11 by default. The PR above leaves the shortcut not set to any key sequence, because I don't know how to do this from a plugin. I am also not sure whether we want plugins to assign shortcuts because this will lead to collisions at some point.

@spyder-ide/core-developers Any comments?

**Comment by ccordoba12** [comment]
Restoring `Alt+Shift+F11`, or perhaps a simpler shortcut, is fine for me.

**Comment by jitseniesen** [comment]
> Restoring `Alt+Shift+F11`, or perhaps a simpler shortcut, is fine for me.

@ccordoba12 @dalthviz Next question, how do I assign a default shortcut? Internal plugins set their default shortcuts in `spyder/config/main.py`, but I don't see a way for this plugin (or other external plugins) to set their default shortcut.

**Comment by dalthviz** [comment]
I think `spyder-line-profiler` sets a shortcut so that could help here! Checking, I think for the shortcut you need to add a `shortcuts` section in the plugin default config definition, so something like:

https://github.com/spyder-ide/spyder-line-profiler/blob/5bffa70b0ebb3cbaed57626e105deee46d891a2c/spyder_line_profiler/spyder/config.py#L17-L22

And then from the action definition set the `register_shortcut` kwarg to `True`, so something like:

https://github.com/spyder-ide/spyder-line-profiler/blob/5bffa70b0ebb3cbaed57626e105deee46d891a2c/spyder_line_profiler/spyder/plugin.py#LL78C1-L86C10

I think the important thing there is to use the name given to the action in the shortcut config definiton. For example, in the case of the line profiler, the action is named `run_profiler_action` (which is used in the action definition as well as in the shortcut config definition)

**Comment by jitseniesen** [comment]
Thanks @dalthviz !
