### ISSUE TITLE
Use python interpreter from preferences to run tests

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder-unittest#65]
Use `<python> -m pytest` (for py.test) to run the tests, where `<python>` is the Python executable set in the preferences. This is useful for systems with more than one Python interpreter and it also resolves the Debian issue from #64.

**Comment by jitseniesen** [comment]
@ccordoba12 Is there a signal emiitted when a user changes a configuration option?

I am wondering how the unittest widget can retrieve the Python executable set in the preferences without referencing the main Spyder application. The plugin can read the Spyder configuration and use that to set a field in the unittest widget to contain the Python executable. If there is a signal when the user changes the configuration, then the plugin can read the configuration again and update the widget with the new value of the executable.

**Comment by stevetracvc** [comment]
Is there a workaround? I just installed the plugin but it is basically useless. I installed spyder into its own conda env, and then I install the spyder kernels into my other conda environments. All tests fail because they use the spyder environment, which doesn't have any packages installed.

**Comment by stevetracvc** [comment]
I started to tackle this issue...I'm not sure where to go though.

I added a file picker to the configdialog so you could manually choose the python executable, then made a few other tweaks so that the start function in RunnerBase would use this executable. Unfortunately, that threw a couple errors because the pytestworker file needs to import from spyder (get_translation) and spyder_unittest (zmqstreamwriter).

If I comment those out and just set the writer to FileStub, the tests execute properly with the chosen python executable. However, I only can see that if I choose the Show Output option from the test menu. Looks like that ZMQ stuff is important for making the nice outputs, which would require me to install spyder and spyter-unittest in every conda environment I need it... :-/

Anyone got any ideas?

**Comment by jitseniesen** [comment]
I think that it's possible to decouple pytestworker from the rest of spyder and spyder-unittest, so that you would only have to install pytestworker and pyzmq. I seem to remember that ZmqStreamWriter does not actually use Qt, only the reader does. That would mean that you only need to install pytestworker and pyzmq into the test environment; I don't know whether pyzmq comes with many dependencies.

**Comment by stevetracvc** [comment]
thanks for the quick reply

the zmq stream writer has these imports unfortunately

```
from qtpy.QtCore import QObject, QProcess, QSocketNotifier, Signal
from qtpy.QtWidgets import QApplication
```

I looked into figuring out how to access the currently chosen python executable, but didn't get anywhere. So my fix works well enough for me for now. If you want to see what I did, I forked this repo 

https://github.com/stevetracvc/spyder-unittest/tree/feat/use-different-python

**Comment by stevetracvc** [comment]
it's more a proof of concept, as I don't bother to make sure the chosen python is actually valid, but I probably could add that pretty easily

**Comment by jitseniesen** [comment]
Ah yes, you are right that the file zmqstream depends on qtpy. That file contains two classes, the stream reader and the stream writer. I think it should be possible to split the file in two, one with the stream reader that depends on qtpy and pyzmq, and one with the stream writer that only depends on pyzmq. As a proof of concept, you can do what you said above: just copy the contents of ZmqStreamWriter into the pytestworker file.

I will have a look at exactly how to access the currently chosen python executable. You are right, getting to this information from the plugin is not straightforward.

**Comment by stevetracvc** [comment]
If you look at my fork, it actually doesn't need to be copied. It just needs to be a relative import rather than a full import seems to work. I just changed `from spyder_unittest.backend.zmqstream import ZmqStreamWriter` to `from zmqstream import ZmqStreamWriter` and no longer need to copy the contents to the pytestworker file

**Comment by jitseniesen** [comment]
I tested out your fork and had a look and I understand now what you are saying. It does seem to work.

What's next? If you are happy with your fork and you want to contribute your code, please open a pull request and I will do a proper review. If you feel there is still something missing, let me know and we'll see what to do about it. I have everything installed in my Spyder environment (I don't use many libraries in my projects) so I don't have a good feeling for what is required if you have separate environments.

**Comment by stevetracvc** [comment]
That's a bit of a philosophical question :smile: 

I haven't tested it with unittest or nose. The important change I made should affect them too, but I don't know for sure. Also, I removed the dependence on the spyder translator in the pytestworker file, falling back to only gettext, do you think that's an issue?

It would probably be best if it could auto load the correct executable from the main spyder config. So if you're planning to dig into that, I'm fine with waiting before it gets incorporated. I'll issue the PR though anyway.

**Comment by stevetracvc** [comment]
@jitseniesen  I just fixed that error, I think. My other tests give a "fixture 'qtbot' not found" error but I think that's just my machine :-/
