### ISSUE TITLE
Use new colors for passed and failed tests

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-unittest#96]
@jitseniesen, I think we could use:

1. A softer shade of red for failed tests. The current color is too strong for my eyes :-)
2. A stronger shade of green for passed tests. The current color seems to me too light for me.

@goanpeca, what do you think?

**Comment by goanpeca** [comment]
Agreed. But we should provide these colors from somewhere in soyder so that each pkugin can relly on this.

**Comment by goanpeca** [comment]
We could have, danger warning information (at least)

**Comment by ccordoba12** [comment]
Right. We already have danger and warning colors defined for the find/replace widget (not exposed as global constants though), so we could use them here too.

**Comment by goanpeca** [comment]
>Right. We already have danger and warning colors defined for the find/replace widget (not exposed as global constants though), so we could use them here too.

Yep something like that :-)

**Comment by ccordoba12** [comment]
Good call! @jitseniesen, what do you think?

**Comment by jitseniesen** [comment]
Using the same colour throughout Spyder is obviously a good thing. The colours from breeze look quite okay. I will make some mock-ups and we can see.

**Comment by jitseniesen** [comment]
Currently, the colours are `#C1FFBA`, `#FF0000` and `#C5C5C5` (cool how github adds the small colour boxes!). This looks as follows (there are more passing than failing tests, since I expect this to happen in practice):
![colour-current](https://user-images.githubusercontent.com/7941918/34470429-96da9cfa-ef28-11e7-9d65-e501b4be6fe8.png)

The find/replace widget uses `#FF5050` for "regexp error" and `#FFAF5A`  for "pattern not found". This is a paler red. If we use `#FF5050` in the unittest widget, it looks as follows:
![colour-findreplace](https://user-images.githubusercontent.com/7941918/34470664-6854643c-ef2e-11e7-9979-e0b8fc0175a2.png)
 
`CodeEditor.error_color` is used to indicate errors in the panel to the right of the editor and is set to `#EA2B0E`. This looks like:
![colour-scrollflag](https://user-images.githubusercontent.com/7941918/34470825-229a3436-ef32-11e7-964e-460b0b751e99.png)

The KDE icon colours for Breeze include `#DA4453` (icon red) and `#2ECC71` (icon green), which looks like:
![colour-breeze](https://user-images.githubusercontent.com/7941918/34471017-7a29049a-ef35-11e7-944b-52d7283be106.png)

Any suggestions? To me the second picture seems perhaps the most readable.

**Comment by ccordoba12** [comment]
> To me the second picture seems perhaps the most readable.

Agreed. I think you should implement that.
